name: Docker Image CI

on:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/hzdr/labhub/app:latest
    - name: Login to the GitHub Package Registry
      if: github.ref == 'refs/heads/master'
      run: docker login -p ${{ secrets.GITHUB_TOKEN }} -u ${{ github.actor }} docker.pkg.github.com
    - name: Publish the image
      if: github.ref == 'refs/heads/master'
      run: docker push docker.pkg.github.com/hzdr/labhub/app:latest
